 <!-- Presentacion simple entrenador Pokemon -->
<div class="">
  <div class="card mb-3 "> <!-- style="max-width: 40px;"> -->                                      
    <div class="row g-0">
      <div class="col-md-4">
        <img src="https://github.com/2Ailu4/TPE-WEB2-Juego-Pokemon/blob/dev/images/trainers/<?=$trainer['nombre_entrenador']?>.jpg?raw=true" class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">Usuario: <?=$trainer['nombre_entrenador']?> </h5>
          <h5 class="card-title">Nivel <?=$trainer['nivel_entrenador']?> </h5>
          <a href="<?=$url?>" class="btn btn-primary">+ Informacion</a>
        </div>
      </div>
    </div>
  </div>
</div>

