 <!-- Perfil del entrenador Pokemon -->
<div class="card">
<img src="https://i0.wp.com/codigoespagueti.com/wp-content/uploads/2023/01/ash-ketchum-fanart-pokemon.jpg" class="img-fluid rounded-start" alt="...">
      <h5 class="card-header">Nivel <?=$trainer['nivel_entrenador']?> </h5>
      <div class="card-body">
        <h5 class="card-title">Usuario: <?=$trainer['nombre_entrenador']?> </h5>
        <p class="card-text">Pueblo: <?=$trainer['ciudad_origen']?></p>
        <a href="<?=$url['trainers']?>" class="btn btn-primary">Volver a ver Jugadores</a>
      </div>
</div>

