 <!-- Perfil del entrenador Pokemon -->
<div class="card">
<img src="https://github.com/2Ailu4/TPE-WEB2-Juego-Pokemon/blob/dev/images/trainers/<?=$trainer['nombre_entrenador']?>.jpg?raw=true" class="img-fluid rounded-start" alt="...">
      <h5 class="card-header">Nivel <?=$trainer['nivel_entrenador']?> </h5>
      <div class="card-body">
        <h5 class="card-title">Usuario: <?=$trainer['nombre_entrenador']?> </h5>
        <p class="card-text">Pueblo: <?=$trainer['ciudad_origen']?></p>
        <a href="<?=$url['trainers']?>" class="btn btn-primary">Volver a ver Jugadores</a>
      </div>
</div>

