<div class="accordion accordion-flush" id="accordionFlushExample">
  <?php foreach($pokemons as $index => $pokemon): ?>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed tipografia" 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#flush-collapse-<?= $index ?>" 
                aria-expanded="false" 
                aria-controls="flush-collapse-<?= $index ?>">
          <?= htmlspecialchars($pokemon->nombre) ?>
        </button>
      </h2>
      <div id="flush-collapse-<?= $index ?>" 
           class="accordion-collapse collapse" 
           aria-labelledby="flush-heading-<?= $index ?>" 
           data-bs-parent="#accordionFlushExample">
        <div class="accordion-body">
          <?php require 'pokemon-detail.phtml'; ?>
        </div>
      </div>
    </div>
  <?php endforeach; ?>
</div>


