
<div class="container text-center">
  <div class="row align-items-center">
    <div class="col d-flex flex-column align-items-center aumentar-img">
        <img src="./images/iniciales-primera-generacion2.png" class="d-block w-100" alt="...">
        <a href="<?=BASE_URL?>add-pokemon" type="button" class="btn btn-outline-primary">Agregar un nuevo Pokemon</a>
    </div>

    <img src="./images/vs.png" class="d-block w-50" alt="...">

    <div class="col d-flex flex-column align-items-center aumentar-img">
        <img src="./images/avatar-entrenadores.png" class="d-block w-100" alt="...">
        <a href="<?=BASE_URL?>register-trainer" type="button" class="btn btn-outline-warning">Agregar un nuevo Entrenador</a>
    </div>
  </div>
</div>


<div class="container text-center redireccion">
    <h1 class="display-4"><em>Ver los entrenadores disponibles y sus Pokemons</em></h1>
    <div class="centered-image">
            <a href="<?=BASE_URL?>trainer-list">
                <img src="./images/flecha.png" alt="Imagen" class="img-fluid w-25">
            </a>
    </div>
</div>


