    </main>

  <!-- main footer -->
    <footer class="d-flex flex-wrap justify-content-center align-items-center py-3 my-4 border-top">
          <div class="align-items-center">
            <span class="text-muted">TPE-WEB2-PT2 2024 TUDAI, UNICEN</span>
          </div>
    </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>